###
GET http://localhost:3000/
###
GET http://localhost:3000/admin
###
GET http://localhost:3000/admin/250
###
POST http://localhost:3000/admin
Content-Type: application/json

{
    "login": "nay",
    "senha" : "1234"
}